name: Release

on:
  release:
    types: [created]

jobs:
  build:
    uses: uukelele-scratch/pybuild/.github/workflows/build.yml@main
    with:
      app_name: "Cesena"
      data_dir: "assets" 
      icon_ico: "assets/icon.ico"
      icon_png: "assets/icon.png"
      version: ${{ github.event.release.tag_name }}
      app_id: "96bf4544-bf4f-4d19-a2a2-bd0e66374699"
      entry_point: "src/main.py"

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-installer/*.exe
            linux-appimage/*.AppImage
            macos-dmg/*.dmg